# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Build Java Application
        run: |
          chmod +x gradlew
          ./gradlew clean build

      - name: Publish Release to Github Package Registry
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Documentation:
    runs-on: ubuntu-latest
    if: "contains(github.ref, 'master')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Build Documentation
        run: |
          git pull
          git config --global user.email "shynixn@email.com" && git config --global user.name "Shynixn CI Actions"
          rm -rf docs/apidocs
          rm -rf docs/wiki/site
          chmod +x gradlew
          ./gradlew generateBukkitJavaDocPages > /dev/null
          ./gradlew generateSpongeJavaDocPages > /dev/null
          ./gradlew generateBungeeCordJavaDocPages > /dev/null
          ./gradlew generateVelocityJavaDocPages > /dev/null
          ./gradlew generateMinestomJavaDocPages > /dev/null
          ./gradlew generateFabricJavaDocPages > /dev/null
          sudo apt-get install -y mkdocs
          pip install mkdocs-material
          pip install Pygments
          cd docs/wiki
          mkdocs build
          cd ..
          cd ..
          git add docs
          git commit --message "Automatic CI Documentation."
          git push --quiet https://Shynixn:${{ secrets.GITHUB_TOKEN }}@github.com/Shynixn/MCCoroutine.git HEAD:master
